services:
  universalStore_db:
    container_name: universalStore_db
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: sidof
      POSTGRES_PASSWORD: sidof1/@
      PGDATA: /data/postgres
    volumes:
      - db:/data/postgres
    ports:
      - 5433:5432
    expose:
      - 5432
    networks:
      - db


  api_universal:
    depends_on:
      - universalStore_db
    container_name: api_universal
    build:
      context: .
      args:
        CONTAINER_PORT: ${CONTAINER_PORT}
    image: api_universal:v1
    restart: unless-stopped
    env_file:
      - ${ENV_FILE}
    ports:
      - ${CONTAINER_PORT}:${HOST_PORT}
    environment:
      SPRING_APPLICATION_JSON: '{
          "spring.datasource.url"  : "jdbc:postgresql://universalStore_db:5432/universal",
          "spring.datasource.username" : "sidof",
          "spring.datasource.password" : "sidof1/@",
          "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.PostgreSQLDialect",
          "spring.jpa.hibernate.ddl-auto" : "update"
        }'
    networks:
      - db

networks:
  db:
    driver: bridge
volumes:
  db: