#SERVER
SERVER_PORT: 8080
ACTIVE_PROFILE: prod
CONTAINER_PORT: 8080
#Database
POSTGRES_USER: sidof
POSTGRES_PASSWORD: sidof1/@
POSTGRES_HOST: localhost
POSTGRES_PORT: 5332
POSTGRES_DATABASE: universal
