#SERVER
SERVER_PORT: 8080
ACTIVE_PROFILE: prod
CONTAINER_PORT: 8080
#Database
POSTGRES_USER: sidof
POSTGRES_PASSWORD: sidof1/@
POSTGRES_HOST: localhost
POSTGRES_PORT: 5332
POSTGRES_DATABASE: universal


#EMAIL CONFIG
EMAIL_HOST: smtp.gmail.com
EMAIL_PORT: 587
EMAIL_ID: sidofdountio406@gmail.com
EMAIL_PASSWORD: esltgpxbdqoonuoc
VERIFY_EMAIL_HOST: http://localhost:${SERVER_PORT}